version: "3.6"
services:
  api:
    image: node:16.15.0-alpine
    container_name: nodex_elastic
    build: .
    ports:
      - 3200:3200
    environment:
      - ES_HOST=elasticsearch
      - NODE_PORT=3000
      - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
    command: node index.js
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elastic_nodex

  elasticsearch:
    container_name: n_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - ./elasticdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      - elastic_nodex

volumes:
  elasticdata:
networks:
  elastic_nodex: